version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: leedz_db
      POSTGRES_USER: leedz_user
      POSTGRES_PASSWORD: leedz_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leedz_user -d leedz_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build: ./backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://leedz_user:leedz_password@database:5432/leedz_db
      JWT_SECRET: dev-jwt-secret-key
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
    restart: unless-stopped

  # Frontend React App
  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: 