name: Deploy to Production

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test step
        run: |
          echo "🚀 Starting deployment..."
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and deploy backend
        run: |
          echo "Building backend..."
          docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/leedz-repo/backend:${{ github.sha }} backend
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/leedz-repo/backend:${{ github.sha }}
          
          echo "Deploying backend..."
          gcloud run deploy ${{ secrets.BACKEND_SERVICE }} \
            --image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/leedz-repo/backend:${{ github.sha }} \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --port=3001 \
            --set-env-vars "NODE_ENV=production,PORT=3001" \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
            --set-env-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
            --set-env-vars "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" \
            --set-env-vars "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            --set-env-vars "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" \
            --set-env-vars "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" \
            --set-env-vars "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" \
            --set-env-vars "MIGRATION_SECRET=${{ secrets.MIGRATION_SECRET }}"

      - name: Build and deploy frontend
        run: |
          echo "Building frontend..."
          docker build \
            --build-arg REACT_APP_API_URL="https://${{ secrets.BACKEND_SERVICE }}-${{ secrets.PROJECT_ID }}.a.run.app/api" \
            --build-arg REACT_APP_GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            --build-arg REACT_APP_ENVIRONMENT="production" \
            -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/leedz-repo/frontend:${{ github.sha }} frontend
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/leedz-repo/frontend:${{ github.sha }}
          
          echo "Deploying frontend..."
          gcloud run deploy ${{ secrets.FRONTEND_SERVICE }} \
            --image us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/leedz-repo/frontend:${{ github.sha }} \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --port=80

      - name: Deployment complete
        run: |
          echo "🎉 Deployment successful!"
          echo "Frontend URL: https://${{ secrets.FRONTEND_SERVICE }}-${{ secrets.PROJECT_ID }}.a.run.app"
          echo "Backend URL: https://${{ secrets.BACKEND_SERVICE }}-${{ secrets.PROJECT_ID }}.a.run.app" 